
all install build world worldbuild worldinstall installg buildg worldbuildg worldinstallg installo buildo worldbuildo worldinstallo :
	lib/jvt/codegen_all.rb

clean cleang cleano worldclean worldcleang worldcleano :

realclean:
	rm -rf ../../cpp/jvt/data/*
