MODULES = \


TEMPLATES = \

SRC = \
	main.C \
	$(MODULES)


HEADERS = \
	$(MODULES:.C=.H) \
	$(TEMPLATES)


#BUILD_DIRS = jvtSampleLibTest1
#INSTALL_DIRS = $(BUILD_DIRS)

BINTGT = jvtSampleLibTest1
SCRIPTSTGT =

#USE_JET=1
#USE_JETSTREAM=1
#USE_LLM=1

JVTLIBS = jvt_SampleLib
#SYSLIBS = rt pthread

include $(JVTROOT)/rules/mkrules.mk
